// <auto-generated />
using System;
using BusinessService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessService.Migrations
{
    [DbContext(typeof(ContexteBdCommerce))]
    partial class ContexteBdCommerceModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessService.Models.Categorie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("BusinessService.Models.Commerce", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("CategorieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("EstValide")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("ProprietaireUtilisateurId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.ToTable("Commerces", (string)null);
                });

            modelBuilder.Entity("BusinessService.Models.HoraireCommerce", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CommerceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstFerme")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<TimeSpan>("HeureFermeture")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HeureOuverture")
                        .HasColumnType("time");

                    b.Property<int>("JourSemaine")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommerceId");

                    b.ToTable("HorairesCommerces", (string)null);
                });

            modelBuilder.Entity("BusinessService.Models.TagCulturel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("TagsCulturels", (string)null);
                });

            modelBuilder.Entity("CommerceTagCulturel", b =>
                {
                    b.Property<Guid>("CommercesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagsCulturelsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CommercesId", "TagsCulturelsId");

                    b.HasIndex("TagsCulturelsId");

                    b.ToTable("CommerceTagCulturel", (string)null);
                });

            modelBuilder.Entity("BusinessService.Models.Commerce", b =>
                {
                    b.HasOne("BusinessService.Models.Categorie", "Categorie")
                        .WithMany("Commerces")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("BusinessService.Models.HoraireCommerce", b =>
                {
                    b.HasOne("BusinessService.Models.Commerce", "Commerce")
                        .WithMany("Horaires")
                        .HasForeignKey("CommerceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commerce");
                });

            modelBuilder.Entity("CommerceTagCulturel", b =>
                {
                    b.HasOne("BusinessService.Models.Commerce", null)
                        .WithMany()
                        .HasForeignKey("CommercesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessService.Models.TagCulturel", null)
                        .WithMany()
                        .HasForeignKey("TagsCulturelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BusinessService.Models.Categorie", b =>
                {
                    b.Navigation("Commerces");
                });

            modelBuilder.Entity("BusinessService.Models.Commerce", b =>
                {
                    b.Navigation("Horaires");
                });
#pragma warning restore 612, 618
        }
    }
}
